

/*renombrar la tabla usando RENAME*/
/* Tabla Empleado*/
CREATE TABLE EMPLEADO 
(
id INT PRIMARY KEY,
nombre VARCHAR(50) NOT NULL,
apellido VARCHAR(50) NOT NULL
);

RENAME TABLE EMPLEADO TO PERSONA;

SHOW TABLES
SELECT * FROM PERSONA;
DESC EMPLEADO 


DESC MUTANTES 
/*Añadiremos una nueva tabla que nos diga
nivel del mutante*/
ALTER TABLE MUTANTES
ADD COLUMN NIVEL INT NOT NULL
AFTER SUPERPODER;

/* ELIMINAR UNA COLUMNA*/
 DROP COLUMN NIVEL;